apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-java-sample
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-java-sample
    spec:
      containers:
      - name: sample-app
        image: mwrona/k8s-java-sample:0.0.1
        imagePullPolicy: IfNotPresent
        #env:
        #- name: SPRING_PROFILES_ACTIVE
        #  value: prod
        ports:
        - containerPort: 8080
