apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-java-sample
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-java-sample
    spec:
      containers:
      - name: sample-app
        image: mwrona/k8s-java-sample:0.0.2
        imagePullPolicy: IfNotPresent
        #env:
        #- name: SPRING_PROFILES_ACTIVE
        #  value: prod
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            #httpHeaders:
            #  - name: X-Custom-Header
            #    value: Awesome
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            #httpHeaders:
            #  - name: X-Custom-Header
            #    value: Awesome
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 1
          failureThreshold: 3
          successThreshold: 1
